package competition.simulation.shooter;

import competition.subsystems.pose.PoseSubsystem;
import competition.subsystems.shooter.ShooterSubsystem;
import competition.subsystems.shooter_feeder.ShooterFeederSubsystem;
import org.ironmaple.simulation.seasonspecific.rebuilt2026.Arena2026Rebuilt;
import xbot.common.controls.actuators.mock_adapters.MockCANMotorController;
import xbot.common.properties.DoubleProperty;
import xbot.common.properties.PropertyFactory;

import javax.inject.Inject;
import javax.inject.Singleton;

import java.util.Random;

import static edu.wpi.first.units.Units.Degrees;
import static edu.wpi.first.units.Units.Inches;
import static edu.wpi.first.units.Units.MetersPerSecond;

@Singleton
public class ShooterSimulator {

    final PoseSubsystem pose;
    final ShooterSubsystem shooter;
    final ShooterFeederSubsystem shooterFeeder;

    final MockCANMotorController shooterMotor;
    final MockCANMotorController shooterFeederMotor;

    final DoubleProperty ballsPerSecond;

    final Random random;

    @Inject
    public ShooterSimulator(PoseSubsystem pose, ShooterSubsystem shooter, ShooterFeederSubsystem shooterFeeder,
                            PropertyFactory pf) {
        pf.setPrefix("Simulator/");
        this.pose = pose;
        this.shooter = shooter;
        this.shooterFeeder = shooterFeeder;

        this.shooterMotor = (MockCANMotorController) shooter.middleShooterMotor;
        this.shooterFeederMotor = (MockCANMotorController) shooterFeeder.shooterFeederMotor;

        this.ballsPerSecond = pf.createPersistentProperty("ballsPerSecond", 10);

        this.random = new Random();
    }

    public boolean isShooting() {
        // TODO: Change to shooter feeder once integrated
        return shooterMotor.getPower() > 0;
    }

    public void updateShooterSimulation(Arena2026Rebuilt arena) {
        if (!isShooting()) {
            return;
        }

        // TODO: Add a count for # of fuel stored in robot so we don't go crazy
        // TODO: Extract constants later
        if (random.nextDouble() < ballsPerSecond.get() / 50.0) {
            // Note: All magic numbers here are generated by ChatGPT
            arena.addPieceWithVariance(
                    pose.getCurrentPose2d().getTranslation(),
                    pose.getCurrentHeading(),
                    Inches.of(20),
                    MetersPerSecond.of(10.0),
                    Degrees.of(80),
                    0.30,
                    0.30,
                    2.0,
                    1.0,
                    2.0
            );
        }
    }
}
