# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

jobs:
 - job: Windows_64_Bit
   pool:
     vmImage: 'windows-latest'
   variables:
     GRADLE_USER_HOME: $(Build.SourcesDirectory)/build/.gradle
   steps:
    - checkout: self
      displayName: 'Checkout sources'
      submodules: true
      clean: true
    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '17'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'
    - task: Cache@2
      inputs:
        key: 'gradle | "$(Agent.OS)" | $(Build.SourcesDirectory)/build.gradle | $(Build.SourcesDirectory)/settings.gradle | $(Build.SourcesDirectory)/gradle/wrapper/gradle-wrapper.properties | $(Build.SourcesDirectory)/vendordeps/*'
        path: $(GRADLE_USER_HOME)
      displayName: 'Cache Gradle dependencies'
    - task: Gradle@3
      inputs:
        gradleWrapperFile: 'gradlew'
        gradleOptions: '-Xmx3072m'
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'
        tasks: 'build'
        options: '--warn'
      env:
        GRADLE_USER_HOME: $(GRADLE_USER_HOME)
    - task: PublishCodeCoverageResults@2
      inputs:
        codeCoverageTool: 'JaCoCo'
        summaryFileLocation: 'build/reports/jacoco/test/jacocoTestReport.xml'
        reportDirectory: 'build/reports/jacoco/test/html'
    - task: Gradle@3
      displayName: Stop gradle daemon
      inputs:
        workingDirectory: ''
        gradleWrapperFile: 'gradlew'
        gradleOptions: '-Xmx3072m'
        tasks: '--stop'
        publishJUnitResults: false
      env:
        GRADLE_USER_HOME: $(GRADLE_USER_HOME)
